apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    visualizer.cluster.x-k8s.io: ""
    visualizer.cluster.x-k8s.io/provider-type: "infrastructure"
  name: resourcegroups.resources.azure.com
