apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
type: Opaque
data:
  # Per-resource Secrets will be created based on a Cluster's AzureClusterIdentity.
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_TENANT_ID: ""
  AZURE_CLIENT_ID: ""
