namespace: default
resources:
  - ../base
  - ../../azure-cluster-identity
  - machine-deployment.yaml

patchesStrategicMerge:
  - ../../azure-cluster-identity/azurecluster-identity-ref.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
