apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
  namespace: default
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        kind: AzureMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: ${CLUSTER_NAME}-control-plane
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: ${CLUSTER_NAME}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterTemplate
      name: ${CLUSTER_NAME}-azure-cluster
  workers:
    machineDeployments:
    - class: ${CLUSTER_NAME}-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: ${CLUSTER_NAME}-md-0
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureMachineTemplate
            name: ${CLUSTER_NAME}-md-0
  patches:
    - definitions:
      - jsonPatches:
        - op: add
          path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/controllerManager/extraArgs/cluster-name
          valueFrom:
            variable: builtin.cluster.name
        - op: replace
          path: /spec/template/spec/kubeadmConfigSpec/files
          valueFrom:
            template: |
              - contentFrom:
                  secret:
                    key: control-plane-azure.json
                    name: "{{ .builtin.controlPlane.machineTemplate.infrastructureRef.name }}-azure-json"
                owner: root:root
                path: /etc/kubernetes/azure.json
                permissions: "0644"
        selector:
          apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: KubeadmControlPlaneTemplate
          matchResources:
            controlPlane: true
      name: controlPlaneAzureJsonSecretName
    - definitions:
      - jsonPatches:
        - op: replace
          path: /spec/template/spec/files
          valueFrom:
            template: |
              - contentFrom:
                  secret:
                    key: worker-node-azure.json
                    name: "{{ .builtin.machineDeployment.infrastructureRef.name }}-azure-json"
                owner: root:root
                path: /etc/kubernetes/azure.json
                permissions: "0644"
        selector:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          matchResources:
            machineDeploymentClass:
              names:
              - ${CLUSTER_NAME}-worker
      name: workerAzureJsonSecretName