name: Lint Documentation
on:
  push:
    paths:
      - "**.md"
    branches:
      - main
  pull_request:
    paths: "**.md"
permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        use-quiet-mode: 'yes'
        config-file: .markdownlinkcheck.json
